version: '2'
services:
    kyc5-app:
        image: kyc5
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://kyc5-postgresql:5432/kyc5
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    kyc5-postgresql:
        extends:
            file: postgresql.yml
            service: kyc5-postgresql
